import { createClient } from '@supabase/supabase-js';

const defaultUrl = 'https://abdwsujajtnkpnorufin.supabase.co';
const defaultKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiZHdzdWphanRua3Bub3J1ZmluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ1ODgxMDUsImV4cCI6MjEwMDE2NDEwNX0.03PNa6F6qlHsruiywm-EG85rFbb5IW0kV0PZ_3jF0xI';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || defaultUrl;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || defaultKey;

export const isSupabaseConfigured = true;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Script SQL para criar a tabela no Supabase SQL Editor
export const SUPABASE_SQL_SETUP = `
-- Execute este script no SQL Editor do seu Supabase (https://supabase.com/dashboard/project/abdwsujajtnkpnorufin/sql)

-- 1. Criação da Tabela de Avaliações
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  product TEXT NOT NULL,
  comment TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Habilitar RLS (Row Level Security) e permitir leitura/escrita pública
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir leitura pública" ON reviews FOR SELECT USING (true);
CREATE POLICY "Permitir inserção pública" ON reviews FOR INSERT WITH CHECK (true);

-- 3. Função para Excluir Avaliações Antigas (Mais de 60 dias)
CREATE OR REPLACE FUNCTION purge_old_reviews(retention_days INT DEFAULT 60)
RETURNS VOID AS $$
BEGIN
  DELETE FROM reviews WHERE created_at < NOW() - (retention_days || ' days')::INTERVAL;
END;
$$ LANGUAGE plpgsql;
`;
